# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

布尔值(Boolean) 主要用于判断真假，True代表真，False代表假 浮点型(float) 整数型(int)

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [1]:
i = 0
for j in range(100):
    if j % 2 == 0:
        i = i - j
    else:
        i = i + j
print(i)

50


1.3  将字符串 s="yoyo" 转换成列表

In [2]:
s="yoyo"
list(s)

['y', 'o', 'y', 'o']

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

In [3]:
for i in range(1,100)[2::3][-10:]:
    print(i)

72
75
78
81
84
87
90
93
96
99


从range(1,100)的第二个位置的数开始，相邻的数字相差3，取最后十个数字循环

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [4]:
class diff():
    def __init__(self, time, high, close):
        self.high = high
        self.close = close
        self.time = time
    def timedif(self):
        return {self.time+ "_dif" : self.high-self.close}
one_dif = diff('one', 15, 7).timedif()
print(one_dif)
two_dif = diff('two', 66, 20).timedif()
print(two_dif)

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

查看列名：df.columns 转置：df.T

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [5]:
import pandas as pd
import numpy as np
import talib as ta
data = pd.read_excel("C:/Users/韩汶衍/Desktop/sz50.xlsx",sheetname='600029.XSHG', index_col='datetime').close

F:\Anaconda\envs\dayu\lib\site-packages\pandas\util\_decorators.py:118: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)


In [6]:
EMA = ta.EMA(np.array(data),10)
print(type(EMA[-5:]))
print(EMA[-5:])

<class 'numpy.ndarray'>
[15.08227205 15.2564044  15.44433088 15.72172526 15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [7]:
symbol = ['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data_dict[s] = pd.read_excel("C:/Users/韩汶衍/Desktop/sz50.xlsx",sheetname=s, index_col='datetime')
PN = pd.Panel(data_dict)  
PN

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume

3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [8]:
PN_array = np.array(PN)
print(PN_array.shape)
print(PN_array[:,-20:,0])

(3, 215, 5)
[[ 13.85  13.82  13.83  14.11  14.25  14.39  15.1   15.15  15.22  14.97
   14.89  14.99  14.71  15.07  15.35  16.    16.04  16.29  16.97  17.05]
 [  8.53   8.56   8.62   8.88   9.25   9.24   9.43   9.25   9.02   9.15
    9.63   9.5    9.9    9.97   9.96   9.49   9.68   9.61   9.63   9.8 ]
 [134.83 134.56 137.5  143.18 143.48 144.15 143.61 143.65 144.35 143.36
  146.41 144.71 148.56 156.53 157.12 157.72 154.99 163.52 168.58 169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [9]:
matrix = np.arange(25).reshape(5,5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
